# Generated by Django 3.1.7 on 2021-04-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(max_length=20)),
                ('image_src', models.CharField(max_length=200)),
                ('navigator_url', models.CharField(max_length=200)),
                ('open_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='four',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image_src', models.CharField(max_length=200)),
                ('navigator_url', models.CharField(default='', max_length=200)),
                ('open_type', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(max_length=20)),
                ('cat_id', models.CharField(max_length=20)),
                ('goods_small_logo', models.CharField(max_length=200)),
                ('goods_introduce', models.CharField(max_length=100)),
                ('goods_name', models.CharField(max_length=100)),
                ('goods_number', models.IntegerField()),
                ('goods_price', models.IntegerField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('upd_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='kinds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(max_length=20)),
                ('cat_chenci', models.IntegerField()),
                ('cat_deleted', models.BooleanField()),
                ('cat_icon', models.CharField(default='', max_length=200)),
                ('cat_level', models.IntegerField()),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_pid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='lou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(default=0)),
                ('loukinds', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
                ('image_src', models.CharField(max_length=200)),
                ('navigator_url', models.CharField(default='', max_length=200)),
                ('open_type', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pics_id', models.CharField(max_length=20)),
                ('pics_mid', models.CharField(max_length=200)),
                ('goods_id', models.CharField(max_length=20)),
            ],
        ),
    ]
