# Generated by Django 3.1.7 on 2021-04-04 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JiaGouapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='goods_id',
            new_name='pgoods_id',
        ),
        migrations.AddField(
            model_name='price',
            name='goods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='JiaGouapp.goods'),
            preserve_default=False,
        ),
    ]
