# Generated by Django 3.1.7 on 2021-04-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JiaGouapp', '0003_address_collect_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lou',
            name='loukinds',
            field=models.CharField(default='', max_length=50),
        ),
    ]
