# Generated by Django 3.1.7 on 2021-04-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JiaGouapp', '0004_auto_20210404_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinds',
            name='cat_tit',
            field=models.CharField(default='', max_length=50),
        ),
    ]
