# Generated by Django 3.1.7 on 2021-04-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JiaGouapp', '0005_kinds_cat_tit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_introduce',
            field=models.CharField(max_length=5000),
        ),
    ]
