# Generated by Django 3.1.7 on 2021-04-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JiaGouapp', '0008_auto_20210406_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='goods',
        ),
    ]
