# Generated by Django 3.1.7 on 2021-04-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JiaGouapp', '0011_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
