# Generated by Django 3.1.7 on 2021-05-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JiaGouapp', '0013_auto_20210519_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
