# Generated by Django 3.1.7 on 2021-05-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JiaGouapp', '0014_order_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='passworld',
            new_name='password',
        ),
    ]
